const cfg = window.GOBUDDY_CONFIG || {};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const store={get:(k,d)=>{try{return JSON.parse(localStorage.getItem('gb_'+k))??d}catch{return d}},set:(k,v)=>localStorage.setItem('gb_'+k,JSON.stringify(v))};
const state={user:store.get('user',null),bookings:store.get('bookings',[]),offers:store.get('offers',[]),saved:store.get('saved',[]),trust:store.get('trust',1),currentRide:null};
const rides=[
 {id:'r1',name:'Ananya K.',initials:'AK',rating:4.9,rides:126,score:94,depart:'07:55',arrive:'08:34',from:'Sector 56 Metro Gate',to:'Cyber City Gate 3',walk:2,detour:4,price:72,tags:['Work verified','Quiet','AC','On-time'],seats:2,work:true,women:true,mood:'Quiet',verified:true,car:'Hyundai i20 • White'},
 {id:'r2',name:'Rohit M.',initials:'RM',rating:4.8,rides:88,score:91,depart:'08:05',arrive:'08:41',from:'Golf Course Road',to:'DLF Phase 2',walk:5,detour:2,price:64,tags:['ID verified','Music okay','No smoking'],seats:1,work:false,women:false,mood:'Music',verified:true,car:'Honda City • Grey'},
 {id:'r3',name:'Neha S.',initials:'NS',rating:5.0,rides:52,score:89,depart:'07:50',arrive:'08:37',from:'Sector 57 Market',to:'Cyber Hub',walk:4,detour:7,price:78,tags:['Work verified','Women preferred','Quiet'],seats:2,work:true,women:true,mood:'Quiet',verified:true,car:'Tata Altroz • Blue'},
 {id:'r4',name:'Arjun P.',initials:'AP',rating:4.7,rides:203,score:86,depart:'08:10',arrive:'08:48',from:'Hong Kong Bazaar',to:'Udyog Vihar Phase 3',walk:6,detour:3,price:61,tags:['Vehicle verified','Chat welcome','AC'],seats:3,work:false,women:false,mood:'Chat',verified:true,car:'Maruti Baleno • Silver'},
 {id:'r5',name:'Meera R.',initials:'MR',rating:4.9,rides:71,score:84,depart:'08:00',arrive:'08:45',from:'Sector 55-56 Metro',to:'Ambience Island',walk:3,detour:8,price:75,tags:['Work verified','Women preferred','No smoking'],seats:1,work:true,women:true,mood:'Quiet',verified:true,car:'Kia Sonet • Black'},
 {id:'r6',name:'Vikram D.',initials:'VD',rating:4.8,rides:141,score:81,depart:'08:15',arrive:'08:52',from:'Sector 54 Chowk',to:'Cyber City',walk:7,detour:5,price:59,tags:['ID verified','Music okay','Luggage okay'],seats:2,work:false,women:false,mood:'Music',verified:true,car:'Nexon EV • White'}
];
const faqs=[
 ['How does GoBuddy calculate a match score?','The prototype combines route overlap, pickup walk, driver detour, timing, trust and selected ride preferences into a single fit score. A production version would calculate road overlap with the Google Routes API.'],
 ['Is GoBuddy a taxi service?','GoBuddy is designed as a carpooling and shared-cost platform: people already travelling a route can share available seats. Commercial classification, insurance and local transport requirements should be reviewed before production launch.'],
 ['How are payments handled?','The prototype supports a Razorpay-ready checkout. Secret credentials stay on the server. A production launch should add webhooks, receipts, cancellation rules, refunds and reconciliation.'],
 ['Can I restrict rides to colleagues?','Yes. GoBuddy Work and Buddy Circles are designed for verified workplace or community groups, while still allowing public matching when users choose it.'],
 ['What if my route changes during a trip?','GoBuddy Safe is designed to surface route-change prompts and live-trip sharing so riders can confirm they are okay or quickly access support.'],
 ['Can I schedule a recurring commute?','Yes. Drivers can select recurring weekdays, while riders can use Commute Autopilot to surface likely matches around saved office routines.'],
 ['How is my home address protected?','The product concept uses approximate pickup zones before acceptance and suggests MeetSpots so exact home locations do not need to be publicly exposed.'],
 ['Can women prefer women co-travellers?','The matching preferences include women-preferred rides. Production rules should be implemented carefully with clear user controls and applicable law.']
];
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function todayDefaults(){const d=new Date(),iso=d.toISOString().slice(0,10);['heroDate','findDate','offerDate'].forEach(id=>{const e=$('#'+id);if(e&&!e.value)e.value=iso});d.setMinutes(d.getMinutes()+30);if(!$('#heroTime').value)$('#heroTime').value=d.toTimeString().slice(0,5);if(!$('#offerTime').value)$('#offerTime').value=d.toTimeString().slice(0,5)}
function route(){const hash=(location.hash||'#home').slice(1),id=['home','find','offer','safety','work','rewards','profile','help'].includes(hash)?hash:'home';$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===id));$('#mobileDrawer').classList.remove('open');window.scrollTo({top:0,behavior:'instant'});if(id==='find')setTimeout(initMap,60);if(id==='profile')renderProfile()}
function openModal(id){const m=$('#'+id);if(m){m.classList.add('open');m.setAttribute('aria-hidden','false')}}function closeModal(m){m.classList.remove('open');m.setAttribute('aria-hidden','true')}
function requireUser(next){if(state.user){next();return}openModal('signupModal');toast('Create a quick profile to continue.')}
function syncUserUI(){const logged=!!state.user;$$('[data-open="loginModal"],[data-open="signupModal"]').forEach(b=>b.classList.toggle('hidden',logged));$('#userAvatar').classList.toggle('hidden',!logged);if(logged){const init=state.user.name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();$('#userAvatar').textContent=init}}
function animateCounts(){$$('[data-count]').forEach(el=>{const target=+el.dataset.count,steps=35;let i=0;const timer=setInterval(()=>{i++;const val=Math.round(target*(i/steps));el.textContent=val.toLocaleString()+(target>=10000?'+':'');if(i>=steps)clearInterval(timer)},30)})}
function filteredRides(){let data=[...rides];if($('#fVerified')?.checked)data=data.filter(r=>r.verified);if($('#fWork')?.checked)data=data.filter(r=>r.work);if($('#fWomen')?.checked)data=data.filter(r=>r.women);const max=+($('#detourRange')?.value||20);data=data.filter(r=>r.detour<=max);const mood=$('#moodFilter')?.value||'Any';if(mood!=='Any')data=data.filter(r=>r.mood===mood);const sort=$('#sortMatches')?.value||'fit';data.sort((a,b)=>sort==='price'?a.price-b.price:sort==='rating'?b.rating-a.rating:sort==='depart'?a.depart.localeCompare(b.depart):b.score-a.score);return data}
function renderRides(){const data=filteredRides(),wrap=$('#rideResults');if(!wrap)return;$('#resultCount').textContent=`${data.length} match${data.length===1?'':'es'}`;$('#searchSummary').textContent=`${$('#findFrom').value||'Pickup'} → ${$('#findTo').value||'Destination'}`;wrap.innerHTML=data.length?data.map(r=>`<article class="ride-card"><div class="ride-main"><div class="ride-time"><strong>${r.depart}</strong><small>${r.score}% match</small><div class="avatar" style="margin-top:16px">${r.initials}</div></div><div><div class="route-compact"><p><strong>${r.from}</strong><small>${r.walk} min walk</small></p><p><strong>${r.to}</strong><small>ETA ${r.arrive} · ${r.detour} min detour</small></p></div><div class="person-row"><div><strong>${r.name}</strong><small>⭐ ${r.rating} · ${r.rides} rides · ${r.car}</small></div><span class="verified">✓</span></div><div class="ride-meta">${r.tags.map(t=>`<span>${t}</span>`).join('')}</div></div></div><div class="ride-price"><button class="save-btn" data-save="${r.id}" aria-label="Save ride">${state.saved.includes(r.id)?'♥':'♡'}</button><div><strong>₹${r.price}</strong><small>estimated share / seat</small></div><button class="btn primary book-btn" data-book="${r.id}">View ride</button></div></article>`).join(''):`<div class="empty-state"><span>🧭</span><h3>No close matches yet</h3><p>Relax a preference or increase maximum detour.</p></div>`;$$('[data-book]').forEach(b=>b.onclick=()=>showRide(rides.find(r=>r.id===b.dataset.book)));$$('[data-save]').forEach(b=>b.onclick=()=>toggleSave(b.dataset.save))}
function toggleSave(id){state.saved=state.saved.includes(id)?state.saved.filter(x=>x!==id):[...state.saved,id];store.set('saved',state.saved);renderRides();toast(state.saved.includes(id)?'Ride saved to your profile.':'Removed from saved rides.')}
function showRide(r){state.currentRide=r;$('#bookingModalContent').innerHTML=`<span class="eyebrow">${r.score}% GoBuddy Match</span><h2>${r.from} → ${r.to}</h2><p style="color:var(--muted);font-size:11px">${r.depart} departure · ETA ${r.arrive} · ${r.detour} min driver detour</p><div class="person-row" style="padding:14px 0"><div class="avatar">${r.initials}</div><div><strong>${r.name}</strong><small>⭐ ${r.rating} · ${r.rides} rides · ${r.car}</small></div><span class="verified">✓</span></div><div class="ride-meta">${r.tags.map(t=>`<span>${t}</span>`).join('')}</div><div style="margin:20px 0;padding:15px;border-radius:14px;background:var(--mint)"><b>₹${r.price} estimated cost share</b><p style="font-size:9px;color:var(--muted)">Demo price for one seat. No surge pricing in this prototype.</p></div><button class="btn primary wide" id="confirmBook">Request this seat →</button>`;openModal('bookingModal');setTimeout(()=>$('#confirmBook').onclick=()=>requireUser(()=>checkout(r)),0)}
async function checkout(r){const amount=r.price*100;if(cfg.RAZORPAY_KEY_ID&&window.Razorpay){try{let orderId;const base=cfg.API_BASE_URL||'';const res=await fetch(base+'/api/payments/order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({amount,rideId:r.id})});if(res.ok){const o=await res.json();orderId=o.id}const z=new Razorpay({key:cfg.RAZORPAY_KEY_ID,amount,currency:'INR',name:'GoBuddy',description:`Ride with ${r.name}`,order_id:orderId,handler:()=>completeBooking(r)});z.open()}catch{toast('Payment service unavailable; using demo booking.');completeBooking(r)}}else{if(confirm(`GoBuddy demo booking\n\nRide with ${r.name}\nEstimated share: ₹${r.price}\n\nPress OK to simulate confirmation.`))completeBooking(r)}}
function completeBooking(r){if(!state.bookings.some(b=>b.id===r.id))state.bookings.unshift({...r,bookedAt:new Date().toISOString()});store.set('bookings',state.bookings);closeModal($('#bookingModal'));toast('Seat requested — demo booking confirmed!');renderProfile()}
function renderOfferPreview(){const from=$('#offerFrom').value||'Your pickup zone',to=$('#offerTo').value||'Your destination',time=$('#offerTime').value||'08:00',price=$('#offerPrice').value||'0',seats=$('#offerSeats').value;$('#offerPreview').innerHTML=`<div style="display:flex;justify-content:space-between"><b>${time}</b><span class="verified">✓</span></div><div class="preview-route"><b>${from}</b><span>Pickup shown approximately before approval</span><b style="margin-top:8px">${to}</b><span>${seats} seats · ₹${price}/seat</span></div><div class="ride-meta">${$$('#prefChips .selected').map(b=>`<span>${b.textContent}</span>`).join('')}</div>`}
function publishOffer(){requireUser(()=>{const offer={id:'o'+Date.now(),from:$('#offerFrom').value,to:$('#offerTo').value,date:$('#offerDate').value,time:$('#offerTime').value,seats:$('#offerSeats').value,price:$('#offerPrice').value,prefs:$$('#prefChips .selected').map(b=>b.textContent),recurring:$('#offerRecurring').checked,days:$$('#weekdayPicker .selected').map(b=>b.textContent)};state.offers.unshift(offer);store.set('offers',state.offers);$('#genericModalContent').innerHTML=`<span class="eyebrow">Ride published</span><h2>Your seats are live in demo mode.</h2><p style="color:var(--muted)">${offer.from} → ${offer.to}<br>${offer.date} at ${offer.time} · ${offer.seats} seat(s) · ₹${offer.price}/seat</p><button class="btn primary wide" data-go-profile>View my rides</button>`;openModal('genericModal');$('[data-go-profile]').onclick=()=>{closeModal($('#genericModal'));location.hash='#profile'}})}
function renderProfile(tab='bookings'){if(!$('#profileContent'))return;const u=state.user,init=u?u.name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase():'GB';$('#profileInitials').textContent=init;$('#profileName').textContent=u?.name||'Guest Buddy';$('#profileEmail').textContent=u?.email||'Sign in to personalize your profile.';$('#trustText').textContent=`${state.trust} / 4 verified`;$$('.trust-level i').forEach((i,n)=>i.classList.toggle('active',n<state.trust));let items=tab==='bookings'?state.bookings:tab==='offers'?state.offers:state.saved.map(id=>rides.find(r=>r.id===id)).filter(Boolean);const c=$('#profileContent');if(!items.length){c.innerHTML=`<div class="empty-state"><span>${tab==='bookings'?'🎫':tab==='offers'?'🚘':'♡'}</span><h3>No ${tab} yet</h3><p>Your GoBuddy activity will appear here.</p></div>`;return}c.innerHTML=items.map(x=>`<div class="mini-booking"><div><b>${x.from} → ${x.to}</b><small>${x.date||x.depart||''} ${x.time||''}</small></div><div><b>${x.price?'₹'+x.price:''}</b><small>${tab==='bookings'?'Confirmed':tab==='offers'?'Published':'Saved ride'}</small></div></div>`).join('')}
function renderFaq(q=''){const f=faqs.filter(x=>(x[0]+' '+x[1]).toLowerCase().includes(q.toLowerCase()));$('#faqGrid').innerHTML=f.map((x,i)=>`<article class="faq-item"><button class="faq-q">${x[0]}<span>＋</span></button><div class="faq-a">${x[1]}</div></article>`).join('');$$('.faq-q').forEach(b=>b.onclick=()=>b.parentElement.classList.toggle('open'))}
let mapLoaded=false;function initMap(){if(mapLoaded||!$('#map')||!cfg.GOOGLE_MAPS_API_KEY)return;window.__goBuddyMapReady=()=>{const el=$('#map'),center={lat:28.4595,lng:77.0266};const map=new google.maps.Map(el,{center,zoom:12,mapTypeControl:false,streetViewControl:false,fullscreenControl:false});new google.maps.Marker({map,position:center,title:'Sample pickup'});['heroFrom','heroTo','findFrom','findTo','offerFrom','offerTo'].forEach(id=>{const input=$('#'+id);if(input)new google.maps.places.Autocomplete(input,{fields:['formatted_address','geometry','name']})})};const s=document.createElement('script');s.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(cfg.GOOGLE_MAPS_API_KEY)}&libraries=places&callback=__goBuddyMapReady`;s.async=s.defer=true;document.head.appendChild(s);mapLoaded=true}
function locate(){if(!navigator.geolocation)return toast('Location is not supported here.');navigator.geolocation.getCurrentPosition(p=>{$('#heroFrom').value=`Current location (${p.coords.latitude.toFixed(5)}, ${p.coords.longitude.toFixed(5)})`;toast('Precise pickup added.')},()=>toast('Location permission was not granted.'),{enableHighAccuracy:true,timeout:8000})}
function generic(title,text,button='Done'){ $('#genericModalContent').innerHTML=`<span class="eyebrow">GoBuddy</span><h2>${title}</h2><p style="color:var(--muted);line-height:1.7">${text}</p><button class="btn primary wide" data-close-generic>${button}</button>`;openModal('genericModal');$('[data-close-generic]').onclick=()=>closeModal($('#genericModal'))}
window.addEventListener('hashchange',route);
window.addEventListener('DOMContentLoaded',()=>{todayDefaults();syncUserUI();renderRides();renderOfferPreview();renderFaq();route();animateCounts();
 $$('[data-route]').forEach(b=>b.onclick=()=>location.hash='#'+b.dataset.route);
 $$('.segment').forEach(b=>b.onclick=()=>{$$('.segment').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#heroSubmitText').textContent=b.dataset.tripmode==='find'?'Show smart matches':'Continue to offer ride'});
 $$('.smart-pill').forEach(b=>b.onclick=()=>b.classList.toggle('selected'));$('#swapHero').onclick=()=>{const a=$('#heroFrom'),b=$('#heroTo');[a.value,b.value]=[b.value,a.value]};$('#useLocationBtn').onclick=locate;
 $('#heroSearchForm').onsubmit=e=>{e.preventDefault();const mode=$('.segment.active').dataset.tripmode,from=$('#heroFrom').value,to=$('#heroTo').value;location.hash=mode==='find'?'#find':'#offer';setTimeout(()=>{if(mode==='find'){$('#findFrom').value=from;$('#findTo').value=to;renderRides()}else{$('#offerFrom').value=from;$('#offerTo').value=to;renderOfferPreview()}},30)};
 ['findFrom','findTo'].forEach(id=>$('#'+id).addEventListener('input',renderRides));['fVerified','fWork','fWomen','moodFilter','sortMatches'].forEach(id=>$('#'+id).addEventListener('change',renderRides));$('#detourRange').oninput=e=>{$('#detourLabel').textContent=e.target.value+' min';renderRides()};$('#refreshMatches').onclick=()=>{renderRides();toast('Matches updated for your preferences.')};$('#resetFilters').onclick=()=>{$('#fVerified').checked=true;$('#fWork').checked=$('#fWomen').checked=false;$('#detourRange').value=10;$('#detourLabel').textContent='10 min';$('#moodFilter').value='Any';$('#sortMatches').value='fit';renderRides()};
 $$('#prefChips button').forEach(b=>b.onclick=()=>{b.classList.toggle('selected');renderOfferPreview()});['offerFrom','offerTo','offerDate','offerTime','offerSeats','offerPrice'].forEach(id=>$('#'+id).addEventListener('input',renderOfferPreview));$('#offerRecurring').onchange=e=>$('#weekdayPicker').classList.toggle('hidden',!e.target.checked);$$('#weekdayPicker button').forEach(b=>b.onclick=()=>b.classList.toggle('selected'));$('#offerForm').onsubmit=e=>{e.preventDefault();publishOffer()};
 $$('#autopilotToggle').forEach(b=>b.onclick=()=>{b.classList.toggle('on');b.querySelector('b').textContent=b.classList.contains('on')?'On':'Off';toast(b.classList.contains('on')?'Commute Autopilot enabled.':'Commute Autopilot paused.')});
 $$('[data-demo="meetspot"]').forEach(b=>b.onclick=()=>generic('MeetSpot preview','Instead of sharing an exact home pin, GoBuddy can suggest a safe pickup zone such as a metro gate, service lane, office entrance or easy stopping point that adds minimal walking and driver detour.'));
 $$('[data-open]').forEach(b=>b.onclick=()=>openModal(b.dataset.open));$$('.modal-close').forEach(b=>b.onclick=()=>closeModal(b.closest('.modal')));$$('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)closeModal(m)});
 $$('.auth-form').forEach(f=>f.onsubmit=e=>{e.preventDefault();const data=new FormData(f);state.user={name:data.get('name'),email:data.get('email'),mobile:data.get('mobile')||''};store.set('user',state.user);syncUserUI();closeModal(f.closest('.modal'));toast(`Welcome to GoBuddy, ${state.user.name.split(' ')[0]}!`);renderProfile()});$$('.demo-google').forEach(b=>b.onclick=()=>{state.user={name:'Demo Buddy',email:'demo@gobuddy.app'};store.set('user',state.user);syncUserUI();closeModal(b.closest('.modal'));toast('Demo Google sign-in complete.')});
 $('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');store.set('dark',document.body.classList.contains('dark'))};if(store.get('dark',false))document.body.classList.add('dark');$('#menuBtn').onclick=()=>$('#mobileDrawer').classList.add('open');$('#drawerClose').onclick=()=>$('#mobileDrawer').classList.remove('open');
 $$('[data-profiletab]').forEach(b=>b.onclick=()=>{$$('[data-profiletab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProfile(b.dataset.profiletab)});$('#verifyProfile').onclick=()=>{if(!state.user)return openModal('signupModal');if(state.trust<4){state.trust++;store.set('trust',state.trust);renderProfile();toast('Demo verification added to your Trust Ring.')}else toast('Your Trust Ring is complete.')};
 $('#faqSearch').oninput=e=>renderFaq(e.target.value);$('#contactSupport').onclick=()=>generic('Support request started','In production this would open secure in-app chat or create a support ticket prefilled with your account and trip context.','Close');$('#safetyDemo').onclick=()=>generic('Safety demo activated','Trip PIN verified ✓\nLive trip sharing enabled ✓\nRoute monitoring enabled ✓\nTrusted contact notified ✓');$('#workDemo').onclick=()=>generic('GoBuddy Work demo','Thanks! In production we would collect company size, commute locations, verification method, security requirements and the right contact for a pilot.');
});
